// MAP SETTINGS
pub const WIDTH: u32 = 20;
pub const HEIGHT: u32 = 10;

// PLAYER/AI SETTINGS
pub const NUM_PLAYERS: u32 = 2;

// TRAINING LOOP SETTINGS
pub const EPISODES: u32 = 2000;
pub const MAX_STEPS_PER_EPISODE: u32 = 200;
