# --- Simulation Parameters ---

# MAP SETTINGS
WIDTH = 10
HEIGHT = 10
OBSTACLE_DENSITY = 0.1
NUM_TREES = 15
NUM_STONE = 10
NUM_SULFUR = 10

# PLAYER/AI SETTINGS
LEARNING_RATE = 0.1
DISCOUNT_FACTOR = 0.9
INITIAL_EPSILON = 1.0
MIN_LEARNING_RATE = 0.01
MAX_LEARNING_RATE = 0.5
LEARNING_RATE_ADJUSTMENT = 0.01

# TRAINING LOOP SETTINGS
EPISODES = 2000
MAX_STEPS_PER_EPISODE = 100
EPSILON_DECAY = 0.999
MIN_EPSILON = 0.05

# TIME SETTINGS
DAY_LENGTH = 100  # in ticks
NIGHT_LENGTH = 50 # in ticks

# WIPE SETTINGS
WIPE_CYCLE = 1000 # number of episodes before a map wipe

# GOAL SETTINGS
WOOD_GOAL = 5 # This will be replaced by crafting goals later
STONE_GOAL = 3 # Example for a new goal
CRAFTING_GOAL = 'stone_axe'
